### ISSUE TITLE
FEATURE: UI changes - improving UX for user commons page

### ISSUE THREAD

**Issue by briggsrr** [ucsb-cs156/proj-happycows#20]
# Feature Summary 
The aim is to enhance the user interface of the commons page to promote clarity and improve user experience. This includes the integration of total player visibility, revamping the profits table for clarity, and possible complete page redesign.

# Discussion

Several UI modifications are necessary. Alternatively, a total page redesign can be considered if a more efficient layout is envisioned.

## 1. Duration Tracking
Revamp the 'Today is day !' feature on the commons page to display the number of days since the commons was established.

<br/>

## 2. Total Players 
Incorporate a mechanism to display the total number of players on the user commons page

<br/>

## 3. Leaderboard Placement 
Redesign the components of the farm stats column: photos, total wealth, and cow health.

<br/>

## 4. Profits Table Refinement
Address ambiguous labels in the profits table, such as the unclear "Amount" column.

<br/>

## 5. Profits Table Display
Refine profit display to show only the most recent 'n' profits, while providing a link to a separate page for users to access their complete profit history.

<br/>

## 6. Redesign the user commons page 
Some things you could do to achieve this: 
 
1. Centering Farm Stats: Center the farm stats column photos, total wealth, and cow health
2. Make key user statistics clear: Change the size of photos to be smaller and make text like total wealth bigger

**Comment by pconrad** [comment]
1. Duration Tracking: Revamp the 'Today is day !' feature on the commons page to display the number of days since the commons was established. **Fixed #44**
2. Total Players Incorporate a mechanism to display the total number of players on the user commons page **Fixed #44**
3. Leaderboard Placement Redesign the components of the farm stats column: photos, total wealth, and cow health. **Fixed #44**
4. Profits Table Refinement: Address ambiguous labels in the profits table, such as the unclear "Amount" column.  **Fixed #44**
5. Profits Table Display
Refine profit display to show only the most recent 'n' profits, while providing a link to a separate page for users to access their complete profit history.  Not fixed in #44; will refactor into separate issue.
6. Redesign the user commons page: Some things you could do to achieve this: Centering Farm Stats: Center the farm stats column photos, total wealth, and cow health; Make key user statistics clear: Change the size of photos to be smaller and make text like total wealth bigger **Fixed #44**
